# Generated by Django 5.0.3 on 2024-04-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="category_type",
            field=models.CharField(
                choices=[("expense", "expense"), ("income", "income")],
                default="expense",
                max_length=8,
            ),
        ),
    ]
